module.exports = {
  projects: [
    ,
    '<rootDir>/apps/web/profile',
    '<rootDir>/libs/web/core',
    '<rootDir>/apps/seek/client',
    '<rootDir>/libs/web/router',
    '<rootDir>/apps/web/recorder',
    '<rootDir>/libs/util/encoder',
    '<rootDir>/apps/web/transfer',
    '<rootDir>/apps/web/phone',
    '<rootDir>/apps/node/server',
    '<rootDir>/apps/node/client',
    '<rootDir>/libs/web/seek/elements',
    '<rootDir>/libs/tool/release',
    '<rootDir>/apps/tool/release-e2e',
    '<rootDir>/libs/web/common',
    '<rootDir>/apps/web/seek',
  ],
}
