name: Pull Request

on: pull_request

env:
  CI: true

jobs:
  check:
    name: Checklist
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Check Format
        run: npm run format:check -- --base origin/main
      - name: Lint Workspace & Code
        run: npm run affected:lint -- --exclude=util-encoder --base=origin/main
      - name: Unit Tests
        run: npm run affected:test -- --base origin/main
      - name: Test Builds
        run: npm run affected:build -- --base origin/main
